# Copyright Â© 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

SAS_LOG_LEVEL_RISKCIRRUSDEPLOYER=INFO
SAS_RISK_CIRRUS_DEPLOYER_SKIP_SPECIFIC_INSTALL_STEPS=
SAS_RISK_CIRRUS_DEPLOYER_RUN_SPECIFIC_INSTALL_STEPS=
SAS_RISK_CIRRUS_SET_WORKFLOW_SERVICE_ACCOUNT_FLG=Y
SAS_RISK_CIRRUS_WORKFLOW_DEFAULT_SERVICE_ACCOUNT=viya_admin
